## 라이브러리

In [1]:
import torch
import numpy as np

### 뷰(view)

파이토치 텐서의 뷰(View)는 넘파이에서의 리쉐이프(Reshape)와 같은 역할을 합니다.  
Reshape라는 이름에서 알 수 있듯이, 텐서의 크기(Shape)를 변경해주는 역할을 합니다.

임의로 3차원 테서를 생성한다.

In [14]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
ft = torch.FloatTensor(t)

print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


3열 2행 2차원 인 것을 확인할 수 있다.

In [39]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

ft1 = ft.view([-1, 3])
print(ft1[-1])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([ 9., 10., 11.])


-1은 첫번째 차원은 사용자가 잘 모르겠으니 파이토치에 맡기겠다는 의미이고, 3은 두번째 차원의 길이는 3을 가지도록 하라는 의미입니다.  
다시 말해 현재 3차원 텐서를 2차원 텐서로 변경하되 (?, 3)의 크기로 변경하라는 의미입니다.  
결과적으로 (4, 3)의 크기를 가지는 텐서를 얻었습니다.

내부적으로 크기 변환은 다음과 같이 이루어졌습니다. (2, 2, 3) -> (2 × 2, 3) -> (4, 3)

In [70]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


그렇다면 (2 × 2 × 3) 텐서를 (? × 1 × 3) 텐서로 변경하라고 하면 ?는 몇 차원인가요?  
위와같이 (2 × 2 × 3) = (? × 1 × 3) = 12를 만족해야 하므로 ?는 4가 됩니다

제일 중요한 것은 원소 개수가 보존된다는 것이다.  

### 스퀴즈(Squeeze)

스퀴즈는 차원이 1인 경우에는 해당 차원을 제거합니다.  
실무에서 텐서가 4차원이 나오면 안 되기 때문에 3차원으로 줄 일 경우에 많이 사용한다

먼저 실습을 위해 임의로 (3 × 1)의 크기를 가지는 2차원 텐서를 만들겠습니다

In [71]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [72]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


위의 결과는 1이었던 두번째 차원이 제거되면서 (3,)의 크기를 가지는 텐서로 변경되어 1차원 벡터가 된 것을 보여줍니다.

In [87]:
shape = (3,1,2)
ones_tensor = torch.ones(shape)
print(ones_tensor, "\n")


print(ones_tensor.squeeze(), "\n")
print(ones_tensor.squeeze().shape)

tensor([[[1., 1.]],

        [[1., 1.]],

        [[1., 1.]]]) 

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) 

torch.Size([3, 2])


3차원에서도 2차원으로 내리는 모습을 볼 수 있다.

### 언스퀴즈(Unsqueeze)

언스퀴즈는 스퀴즈와 정반대입니다. 특정 위치에 1인 차원을 추가할 수 있습니다

In [88]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [89]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [90]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


좀 더 쉽게 설명한다면 배열의 요소 위치에 차원을 추가한다고 보면 된다.  
이미 그 위치에 차원이 존재한다면 뒤로 밀려난다.

In [101]:
shape = (3,4,2)
o= torch.ones(shape)
print(o.shape, "\n")

print(o.unsqueeze(1).shape, "\n")
print(o.unsqueeze(-1).shape)

torch.Size([3, 4, 2]) 

torch.Size([3, 1, 4, 2]) 

torch.Size([3, 4, 2, 1])
